edition = "2023";

package gophkeeper;

option go_package = "gophKeeper/internal/proto/gen";

import "common.proto";

// FileItem представляет метаданные файла
message FileItem {
    string local_id = 1;   // Локальный идентификатор клиента
    string server_id = 2;  // Идентификатор на сервере
    string name = 3;       // Имя файла
    string metadata = 4;   // Дополнительные метаданные
    int64 size = 5;        // Размер файла в байтах
    string checksum = 6;   // Контрольная сумма метаданных для синхронизации
    TimeMap timemap = 7;   // Временные метки
    bool deleted = 8;      // Флаг удаления (soft delete)
}


message RemoveFileRequest {
    string local_id = 1;
}

message RemoveFileResponse {}

message GetFilesRequest {}

message GetFilesResponse {
    repeated FileItem files = 1;
}

message FilesSyncRequest {
    repeated FileItem files = 1;
}

service FileService {
    rpc UpdateFile(FileItem) returns (Response);
    rpc RemoveFile(RemoveFileRequest) returns (RemoveFileResponse);
    rpc GetFiles(GetFilesRequest) returns (GetFilesResponse);
    rpc FilesShortSync(ShortSyncRequest) returns (ShortSyncResponse);
    rpc FilesSync(FilesSyncRequest) returns (GetFilesResponse);
}