edition = "2023";

package gophkeeper;

option go_package = "gophKeeper/internal/proto/gen";

import "common.proto";

message PasswordItem {
    string local_id = 1;
    string server_id = 2;
    string login = 3;
    string password = 4;
    string description = 5;
    TimeMap timemap = 6;
    bool deleted = 7;
}

message PasswordResponse {
    string server_id = 1;
}

message RemovePasswordRequest {
    string local_id = 1;
}

message RemovePasswordResponse {}

message GetPasswordsRequest {}

message GetPasswordsResponse {
    repeated PasswordItem passwords = 1;
}

message PasswordsSyncRequest {
    repeated PasswordItem passwords= 1;
}

service PasswordService {
    rpc UpdatePassword(PasswordItem) returns (PasswordResponse);
    rpc RemovePassword(RemovePasswordRequest) returns (RemovePasswordResponse);
    rpc GetPasswords(GetPasswordsRequest) returns (GetPasswordsResponse);
    rpc PasswordsSync(PasswordsSyncRequest) returns (GetPasswordsResponse);
}