edition = "2023";

package gophkeeper;

option go_package = "gophKeeper/pkg/proto";

import "common.proto";

// NoteItem представляет текстовую заметку
message NoteItem {
    string local_id = 1; // Локальный идентификатор клиента
    string server_id = 2; // Идентификатор на сервере
    string title = 3; // Заголовок заметки (зашифрован, base64)
    string text = 4; // Текст заметки (зашифрован, base64)
    string checksum = 5; // Контрольная сумма для синхронизации
    TimeMap timemap = 6; // Временные метки
    bool deleted = 7; // Флаг удаления (soft delete)
}

message RemoveNoteRequest {
    string local_id = 1;
}

message RemoveNoteResponse {}

message GetNotesRequest {}

message GetNotesResponse {
    repeated NoteItem notes = 1;
}

message NotesSyncRequest {
    repeated NoteItem notes = 1;
}

service NoteService {
    rpc UpdateNote(NoteItem) returns (Response);
    rpc RemoveNote(RemoveNoteRequest) returns (RemoveNoteResponse);
    rpc GetNotes(GetNotesRequest) returns (GetNotesResponse);
    rpc NotesSync(NotesSyncRequest) returns (GetNotesResponse);
}