edition = "2023";

package gophkeeper;

option go_package = "gophKeeper/pkg/proto";

import "common.proto";

// PasswordItem представляет данные пароля (логин/пароль)
message PasswordItem {
    int64 local_id = 1; // Локальный идентификатор клиента
    int64 server_id = 2; // Идентификатор на сервере
    string login = 3; // Логин (зашифрован, base64)
    string password = 4; // Пароль (зашифрован, base64)
    string description = 5; // Описание/название (зашифрован, base64)
    string checksum = 6; // Контрольная сумма для синхронизации
    int64 change_time = 7; // Временные метки
    bool deleted = 8; // Флаг удаления (soft delete)
    int32 version = 9; // Версия записи
}

message RemovePasswordRequest {
    int64 local_id = 1;
}

message RemovePasswordResponse {}

message GetPasswordsRequest {}

message GetPasswordsResponse {
    repeated PasswordItem passwords = 1;
}

message PasswordsSyncRequest {
    repeated PasswordItem passwords = 1; // Пароли для синхронизации
}

service PasswordService {
    rpc UpdatePassword(PasswordItem) returns (Response);
    rpc RemovePassword(RemovePasswordRequest) returns (RemovePasswordResponse);
    rpc GetPasswords(GetPasswordsRequest) returns (GetPasswordsResponse);
    rpc PasswordsSync(PasswordsSyncRequest) returns (GetPasswordsResponse);
}