// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ShortItem представляет краткую информацию об элементе для синхронизации
type ShortItem struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_LocalId     int64                  `protobuf:"varint,1,opt,name=local_id,json=localId"`
	xxx_hidden_ServerId    int64                  `protobuf:"varint,2,opt,name=server_id,json=serverId"`
	xxx_hidden_Checksum    *string                `protobuf:"bytes,3,opt,name=checksum"`
	xxx_hidden_Type        *string                `protobuf:"bytes,4,opt,name=type"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ShortItem) Reset() {
	*x = ShortItem{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortItem) ProtoMessage() {}

func (x *ShortItem) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ShortItem) GetLocalId() int64 {
	if x != nil {
		return x.xxx_hidden_LocalId
	}
	return 0
}

func (x *ShortItem) GetServerId() int64 {
	if x != nil {
		return x.xxx_hidden_ServerId
	}
	return 0
}

func (x *ShortItem) GetChecksum() string {
	if x != nil {
		if x.xxx_hidden_Checksum != nil {
			return *x.xxx_hidden_Checksum
		}
		return ""
	}
	return ""
}

func (x *ShortItem) GetType() string {
	if x != nil {
		if x.xxx_hidden_Type != nil {
			return *x.xxx_hidden_Type
		}
		return ""
	}
	return ""
}

func (x *ShortItem) SetLocalId(v int64) {
	x.xxx_hidden_LocalId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *ShortItem) SetServerId(v int64) {
	x.xxx_hidden_ServerId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *ShortItem) SetChecksum(v string) {
	x.xxx_hidden_Checksum = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *ShortItem) SetType(v string) {
	x.xxx_hidden_Type = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *ShortItem) HasLocalId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ShortItem) HasServerId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ShortItem) HasChecksum() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ShortItem) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ShortItem) ClearLocalId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_LocalId = 0
}

func (x *ShortItem) ClearServerId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ServerId = 0
}

func (x *ShortItem) ClearChecksum() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Checksum = nil
}

func (x *ShortItem) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Type = nil
}

type ShortItem_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	LocalId  *int64
	ServerId *int64
	Checksum *string
	Type     *string
}

func (b0 ShortItem_builder) Build() *ShortItem {
	m0 := &ShortItem{}
	b, x := &b0, m0
	_, _ = b, x
	if b.LocalId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_LocalId = *b.LocalId
	}
	if b.ServerId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_ServerId = *b.ServerId
	}
	if b.Checksum != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Checksum = b.Checksum
	}
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Type = b.Type
	}
	return m0
}

// Response используется для возврата server_id после операций
type Response struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ServerId    int64                  `protobuf:"varint,1,opt,name=server_id,json=serverId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Response) GetServerId() int64 {
	if x != nil {
		return x.xxx_hidden_ServerId
	}
	return 0
}

func (x *Response) SetServerId(v int64) {
	x.xxx_hidden_ServerId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *Response) HasServerId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Response) ClearServerId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ServerId = 0
}

type Response_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ServerId *int64
}

func (b0 Response_builder) Build() *Response {
	m0 := &Response{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ServerId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_ServerId = *b.ServerId
	}
	return m0
}

// ShortSyncResponse возвращает список локальных ID элементов, которые нужно синхронизировать полностью
type ShortSyncResponse struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_LocalIds  []int64                `protobuf:"varint,1,rep,packed,name=local_ids,json=localIds"`
	xxx_hidden_ServerIds []int64                `protobuf:"varint,2,rep,packed,name=server_ids,json=serverIds"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ShortSyncResponse) Reset() {
	*x = ShortSyncResponse{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortSyncResponse) ProtoMessage() {}

func (x *ShortSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ShortSyncResponse) GetLocalIds() []int64 {
	if x != nil {
		return x.xxx_hidden_LocalIds
	}
	return nil
}

func (x *ShortSyncResponse) GetServerIds() []int64 {
	if x != nil {
		return x.xxx_hidden_ServerIds
	}
	return nil
}

func (x *ShortSyncResponse) SetLocalIds(v []int64) {
	x.xxx_hidden_LocalIds = v
}

func (x *ShortSyncResponse) SetServerIds(v []int64) {
	x.xxx_hidden_ServerIds = v
}

type ShortSyncResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	LocalIds  []int64
	ServerIds []int64
}

func (b0 ShortSyncResponse_builder) Build() *ShortSyncResponse {
	m0 := &ShortSyncResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_LocalIds = b.LocalIds
	x.xxx_hidden_ServerIds = b.ServerIds
	return m0
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\n" +
	"gophkeeper\"s\n" +
	"\tShortItem\x12\x19\n" +
	"\blocal_id\x18\x01 \x01(\x03R\alocalId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\x03R\bserverId\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\tR\bchecksum\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"'\n" +
	"\bResponse\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\x03R\bserverId\"O\n" +
	"\x11ShortSyncResponse\x12\x1b\n" +
	"\tlocal_ids\x18\x01 \x03(\x03R\blocalIds\x12\x1d\n" +
	"\n" +
	"server_ids\x18\x02 \x03(\x03R\tserverIdsB\x16Z\x14gophKeeper/pkg/protob\beditionsp\xe8\a"

var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_proto_goTypes = []any{
	(*ShortItem)(nil),         // 0: gophkeeper.ShortItem
	(*Response)(nil),          // 1: gophkeeper.Response
	(*ShortSyncResponse)(nil), // 2: gophkeeper.ShortSyncResponse
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
